repo: "responsive-icon-cards"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing
  - responsive-css
  - responsive-font-sizes
  - screenshots-all

html:
  - path: "index.html"
    outline: false
    has:
      - "ul"
      - "ul li"
      - "ul div"
      - "ul img"
      - "ul h2"
      - "ul p"
    search:
      - 'placeholder-circle\.svg'
      - 'Atlas moth'
      - 'Hercules Moth'
      - 'Hercules Moth'

css:
  - path: "css/main.css"
    has:
      - ['.cards', 'list-style-type', 'none']
      - ['.card']
      - ['.card-img img']
      - ['.card-body h2']
      - ['.card-body p']
      - ['@25em', '.card-img']
    search:
      - '100%'
      - '1\.3'
      - 'display: inline-block'
      - 'display: block'
    search_not:
      - ['float:', 'Use `display: inline-block` instead of float to complete this assignment']
